name: Bug report
description: Report a bug in Void Reborn
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. nightly / commit hash
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
        - macOS
        - Other
